name: Manual Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to interact with'
        required: true
        default: 'main'
      draft:
        description: 'Indicate if the release should be marked as a draft'
        required: false
        default: 'true'
      prerelease:
        description: 'Indicate if the release should be marked as a prerelease'
        required: false
        default: 'false'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Gitmoji Auto Release
        id: auto_release
        uses: n-ramos/gitmoji-auto-release-action@v1.0.1
        with:
          branch: ${{ github.event.inputs.branch }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
